# Generated by Django 4.1.3 on 2022-11-05 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advocates', '0002_remove_advocates_id_alter_advocates_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocates',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advocates',
            name='username',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
