# Generated by Django 4.1.3 on 2022-11-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0003_advocates_owner_alter_advocates_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocates',
            name='name',
        ),
    ]
