# Generated by Django 4.1.3 on 2022-11-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0005_alter_advocates_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advocates',
        ),
    ]
